console.log(Boolean(10));
console.log(Boolean(true));
console.log(Boolean(false));
console.log(Boolean({}));
console.log(Boolean(undefined));
console.log(Boolean(null));
console.log(Boolean(''));
console.log(Boolean('abba'));
console.log(Boolean(0));